const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const file=path.join(__dirname,'../dist/loot.js');
assert.ok(fs.existsSync(file),'Persistent loot model must exist');
const ctx={console};vm.createContext(ctx);vm.runInContext(fs.readFileSync(file,'utf8'),ctx);const L=ctx.DenkmalLoot;
const mem=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),data}};
let count=0;function test(name,fn){fn();count++;console.log('PASS',name)}
test('Fresh profile retains original three starter powers',()=>{const m=L.create({storage:mem()});assert.equal(m.snapshot().length,3);assert.equal(L.totals(m.snapshot()).powers.ember,true);assert.equal(m.profile.bag.length,0)});
test('Finds persist; identical IDs cannot be picked up twice',()=>{const s=mem(),m=L.create({storage:s});const i=m.generate(5,true);assert.ok(m.add(i));assert.equal(m.add(i),false);const restored=L.create({storage:s});assert.equal(restored.profile.bag[0].id,i.id);assert.ok(['epic','legendary'].includes(i.rarity))});
test('Equipment and destructive commands reject all non-menu contexts',()=>{let menu=true;const m=L.create({storage:mem(),canManage:()=>menu});const i=m.generate(3);m.add(i);menu=false;const before=m.exportJSON();assert.equal(m.equip(i.id,i.slot),false);assert.equal(m.unequip('weapon'),false);assert.equal(m.salvage(i.id),false);assert.equal(m.favorite(i.id),false);assert.equal(m.reforge(i.id),false);assert.equal(m.importJSON(before),false);assert.equal(m.exportJSON(),before)});
test('Run snapshot remains stable after future equipment changes',()=>{const m=L.create({storage:mem()});const snap=m.snapshot(),before=JSON.stringify(snap);const i=m.generate(10);m.add(i);assert.ok(m.equip(i.id,i.slot));assert.equal(JSON.stringify(snap),before);assert.equal(L.create({storage:m.storage}).profile.equipped[i.slot],i.id)});
test('Overflow retains all finds and fills freed backpack cells',()=>{const m=L.create({storage:mem()});for(let n=0;n<35;n++)m.add(m.generate(1));assert.equal(m.profile.bag.length,30);assert.equal(m.profile.overflow.length,5);assert.ok(m.salvage(m.profile.bag[0].id));assert.equal(m.profile.bag.length,30);assert.equal(m.profile.overflow.length,4)});
test('Favorites and equipped items cannot be salvaged or reforged',()=>{const m=L.create({storage:mem()});const i=m.generate(2);m.add(i);m.favorite(i.id);assert.equal(m.salvage(i.id),false);assert.equal(m.reforge(i.id),false);assert.equal(m.salvage(m.profile.equipped.weapon),false)});
test('Import is validated atomically and preserves original on malformed values',()=>{const m=L.create({storage:mem()});const before=m.exportJSON();assert.equal(m.importJSON('{'),false);assert.equal(m.importJSON(JSON.stringify({version:99})),false);const bad=JSON.parse(before);bad.profile.bag.push({...bad.profile.items[0],id:'bad',stats:{damage:Infinity}});assert.equal(m.importJSON(JSON.stringify(bad)),false);assert.equal(m.exportJSON(),before)});
test('Export/import round-trip includes favorites and no duplicate items',()=>{const m=L.create({storage:mem()});const i=m.generate(8,true);m.add(i);m.favorite(i.id);const other=L.create({storage:mem()});assert.ok(other.importJSON(m.exportJSON()));assert.equal(other.profile.bag[0].favorite,true);const bad=JSON.parse(m.exportJSON());bad.profile.overflow.push(bad.profile.bag[0]);assert.equal(other.importJSON(JSON.stringify(bad)),false)});
test('Blocked storage never crashes and exposes a session-only warning',()=>{const m=L.create({storage:{getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}}});assert.ok(m.add(m.generate(1)));assert.match(m.status,/Sitzung/);assert.equal(m.profile.bag.length,1)});
test('Corrupt primary recovers backup; unknown versions are not overwritten',()=>{const s=mem(),m=L.create({storage:s});m.add(m.generate(1));const savedId=m.profile.bag[0].id;m.add(m.generate(2));s.setItem(L.KEY,'{bad');const recovered=L.create({storage:s});assert.match(recovered.status,/Sicherung/);assert.equal(recovered.readOnly,false);assert.equal(recovered.profile.bag[0].id,savedId);const future='{"version":99}';s.setItem(L.KEY,future);const locked=L.create({storage:s});assert.equal(locked.readOnly,true);assert.equal(locked.add(locked.generate(2)),false);assert.equal(s.getItem(L.KEY),future)});
test('Random rolls and aggregate stats stay finite and capped',()=>{const m=L.create({storage:mem(),rng:()=>.999999});const i=m.generate(999999,true);assert.ok(i.level<=30);const stats=L.totals(Array.from({length:8},()=>i));for(const [k,v] of Object.entries(stats))if(k!=='powers')assert.ok(Number.isFinite(v));assert.ok(stats.crit<=.35);assert.ok(stats.defense<=.6);assert.ok(stats.speed<=.5)});
test('Milestone rewards are permanent and awarded exactly once',()=>{const m=L.create({storage:mem()});assert.equal(m.milestone(4),true);const n=m.profile.bag.length;assert.equal(m.milestone(4),false);assert.equal(m.profile.bag.length,n)});
test('Concurrent tabs cannot overwrite newer finds',()=>{const s=mem(),a=L.create({storage:s}),b=L.create({storage:s});a.add(a.generate(1));const current=s.getItem(L.KEY);assert.equal(b.add(b.generate(2)),false);assert.equal(b.readOnly,true);assert.equal(s.getItem(L.KEY),current)});
test('Reforge spends saved essence, keeps rarity/power and honors favorites',()=>{const m=L.create({storage:mem()});for(let n=0;n<10;n++){const i=m.generate(4,true);m.add(i);m.salvage(i.id);}const i=m.generate(10,true);m.add(i);const before=m.profile.essence;assert.ok(m.reforge(i.id));assert.equal(m.profile.essence,before-50);assert.equal(m.find(i.id).rarity,i.rarity);assert.equal(m.find(i.id).power,i.power)});
test('Unavailable localStorage getter does not crash initialization',()=>{const x={};Object.defineProperty(x,'localStorage',{get(){throw Error('SecurityError')}});vm.createContext(x);vm.runInContext(fs.readFileSync(file,'utf8'),x);assert.doesNotThrow(()=>x.DenkmalLoot.create());});
test('Import from a stale tab must not overwrite a newer collection',()=>{const s=mem(),a=L.create({storage:s}),b=L.create({storage:s}),backup=b.exportJSON();a.add(a.generate(5));const newer=s.getItem(L.KEY);assert.equal(b.importJSON(backup),false);assert.equal(s.getItem(L.KEY),newer)});

test('Unsafe imported item sequence is rejected before it can break future drops',()=>{const m=L.create({storage:mem()}),bad=JSON.parse(m.exportJSON());bad.profile.nextId=Number.MAX_SAFE_INTEGER;assert.equal(m.importJSON(JSON.stringify(bad)),false);assert.ok(m.add(m.generate(1)))});
console.log(count+' loot checks passed');
